### PR TITLE
docs: Update RULES.md

### PR DESCRIPTION
**Pull request by a-frantz**
_Describe the problem or feature in addition to a link to the issues._

The `RULES.md` file got out of date. Reiterating something we all know, this isn't a sustainable documentation solution. Not sure the exact priority for updating `sprocket.bio` with pages for each rule, but that is the end-game here.

Before submitting this PR, please make sure:

- [x] You have added a few sentences describing the PR here.
- [x] You have added yourself or the appropriate individual as the assignee.
- [x] You have added at least one relevant code reviewer to the PR.
- [x] Your code builds clean without any errors or warnings.
- [x] You have added tests (when appropriate).
- [x] You have updated the README or other documentation to account for these
      changes (when appropriate).
- [x] You have added an entry to the relevant `CHANGELOG.md` (see
      ["keep a changelog"] for more information).
- [x] Your commit messages follow the [conventional commit] style.

[conventional commit]: https://www.conventionalcommits.org/en/v1.0.0/#summary
["keep a changelog"]: https://keepachangelog.com/en/1.0.0/

### CODE REVIEW

**Review by adthrasher — COMMENTED** [review]
At this point, can we consider removing this file? Or at least making it auto-generated? I'd much rather see a CI step (or something) that loads the `wdl-lint` package, gets the rules, and writes them to a file if we want to have a textual version.

**Comment by a-frantz** [comment]
> At this point, can we consider removing this file? Or at least making it auto-generated? I'd much rather see a CI step (or something) that loads the `wdl-lint` package, gets the rules, and writes them to a file if we want to have a textual version.

That seems doable. I don't have an exact vision for what it looks like though. Spitballing: It could be written into the `ci` crate as a command. Something like `cargo run --bin ci -- lint-docs`. It could recreate the `RULES.md` file pretty easily. IDK how that then gets integrated into `docs.rs` or otherwise displayed though.

**Comment by peterhuene** [comment]
I agree that having this automated would be ideal and putting it in the `ci` crate makes sense to me.

I think we can keep the `RULES.md` file committed in git so that we generate docs like we do now, but have a CI job that also passes a `--check` flag to the `ci` command that will fail if the generated `RULES.md` doesn't match what's on disk.

**Comment by a-frantz** [comment]
There should be a `BLESS` mechanism that will create the RULES.md file from scratch. That way we don't have to bother with writing it by hand or pretty-formatting the file.

**Comment by a-frantz** [comment]
I'm leaning towards having it in `wdl-lint` and operating similar to our other tests, as opposed to the `ci` crate.

**Comment by a-frantz** [comment]
Do we want to merge this PR or not? It probably doesn't make a difference, as I would hope this automation could be completed in time for the next release (whenever that is).

**Review by peterhuene — APPROVED** [review]
Might as well merge it and ensure that whatever automation we create ends up basically not changing what we think is correct.

**Pull request merged**
