### PR TITLE
chore: add a MSRV to each crate and CI job to verify.

### PR DESCRIPTION
**Pull request by peterhuene**
Also updates the README with information about our MSRV policy and instructions for updating.

Before submitting this PR, please make sure:

- [x] You have added a few sentences describing the PR here.
- [x] You have added yourself or the appropriate individual as the assignee.
- [x] You have added at least one relevant code reviewer to the PR.
- [x] Your code builds clean without any errors or warnings.
- [x] You have added tests (when appropriate).
- [x] You have updated the README or other documentation to account for these
      changes (when appropriate).
- [x] You have added an entry to the relevant `CHANGELOG.md` (see
      ["keep a changelog"] for more information).
- [x] Your commit messages follow the [conventional commit] style.

[conventional commit]: https://www.conventionalcommits.org/en/v1.0.0/#summary
["keep a changelog"]: https://keepachangelog.com/en/1.0.0/

### CODE REVIEW

**Review by a-frantz — COMMENTED** [review]
I assume there is a reason for this, but wouldn't it be easier to specify the rust version once for the workspace instead of per-crate?

**Comment by peterhuene** [comment]
As far as I can tell, it's not supported to be specified at the workspace-level.

**Comment by peterhuene** [comment]
No wait, I'm wrong. I'll update.

**Comment by peterhuene** [comment]
So while the manifest supports it, seems like `cargo-msrv` doesn't.

Looking into a workaround.

**Review by a-frantz — APPROVED** [review]

**Comment by peterhuene** [comment]
Sigh, the latest beta release of `cargo-msrv` works fine locally, but exits 1 with nothing printed in CI. 😭

**Pull request merged**
